version: '3.8'

services:
  api:
    build: ./services/api
    image: dmitry123123/flask_api
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/api/:/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flask_dev
volumes:
  postgres_data: